### ISSUE TITLE
unable to successfully complete run.sh for SaaS Permissions service API

### ISSUE THREAD

**Issue by indemnityjames** [Azure/azure-saas#226] opened 2023-05-28 05:00 UTC
**Describe the bug**
Following the instructions of the Identity Framework, I was able to complete a successful deployment.

Running ./setup.sh from src/Saas.Identity/Saas.Permissions/deployment completes successfully.

But when attempting to ./run.sh from the previous folder, I get an error:

### SaaS Administration Service API ###
Provisioning the SaaS Administration Service API...
The file /asdk/src/Saas.Identity/Saas.Permissions/deployment/bicep/parameters/app-service-parameters.json does not exist, creating it now
cp: cannot stat '/asdk/src/Saas.Identity/Saas.Permissions/deployment/bicep/parameters/parameters-template.json': No such file or directory

I tried to manually create the directory and copy the file over manually, but this did not work
I also tried to run src/Saas.Lib/Deployment.Script.Modules/deploy-app-service.sh manually but I must need the wrapper scripts first as I got the error 
./deploy-app-service.sh: line 8: ASDK_DEPLOYMENT_SCRIPT_PROJECT_BASE: unbound variable

![Screenshot 2023-05-28 165930](https://github.com/Azure/azure-saas/assets/134180636/6ed80172-6c39-4249-9383-34f981ec24c7)

**Comment by 1iveowl** [comment] 2023-05-28 11:43
Hi @indemnityjames. Did you just fork the repo recently? If not, please try and sync your repo to get the latest version. There was a bug related to this that was fixed a few weeks ago. 

The error you are getting is that the file `.../parameters-template.json` is missing or that the path is wrong. 

You may want to take a look at this discussion #217 

Let me know if this helps?

Thanks

**Comment by indemnityjames** [comment] 2023-05-29 06:08
Hi @1iveowl thanks for coming back to me.
I had forked recently and I went back to check I am in sync:
      This branch is not behind the upstream Azure:main
      No new commits to fetch. Enjoy your day!

I did an update: sudo apt update && sudo apt upgrade

I blew away the clone on the WSL 2.0 Ubuntu and recloned it
I coped the config.json into the Identity folder to remove that first error 

then I reran ./run.sh in the SaaS.Permissions/deployment folder again, but still get the same error:
      ### SaaS Administration Service API ###
      Provisioning the SaaS Administration Service API...
      The file /asdk/src/Saas.Identity/Saas.Permissions/deployment/bicep/parameters/app-service-parameters.json does not exist, creating it now
      cp: cannot stat '/asdk/src/Saas.Identity/Saas.Permissions/deployment/bicep/parameters/parameters-template.json': No such file or directory

**Comment by 1iveowl** [comment] 2023-05-29 09:21
Thank you. 

I found the issue. In our repo we've renamed the folder `.\bicep\Parameters` to ".\bicep\parameters" lowercase, but for some reason Git is now acknowledging this. Will make an update asap.

**Comment by 1iveowl** [comment] 2023-05-29 09:42
Should be fixed with commit d020e20 and ebcb2be

**Comment by 1iveowl** [comment] 2023-05-29 09:50
@indemnityjames please confirm that you can make it work now?

**Comment by 1iveowl** [comment] 2023-05-30 07:44
You write that you are publishing to a new subscription, right? 

I wonder if it's using the  config.json file referencing a non existing resource group for this new subscription. 

Can you look for a resource group with 88su in it in your subscription?

**Comment by indemnityjames** [comment] 2023-05-30 07:45
that RG exists in Azure, I did delete the old config.json before running SaaS.IdentityProvider again

**Comment by 1iveowl** [comment] 2023-05-30 12:59
I tried to run the script from WSL with the latest changes and I'm unable to reproduce the issue you outline.

I started with a whole new deployment. The Identity Provider runs first and then I deploy Saas.Permissions and this works too.

Do you have more logs or could you try and delete everything and try again from the very beginning?

**Comment by indemnityjames** [comment] 2023-06-07 04:11
thanks @1iveowl 
I deleted all the SaaS.Identity Azure resource and deleted the clone from the Ubuntu WSL
I recloned and reinstalled the SaaS.Identity into a new version 'i4kg'
But when I try and install the SaaS.Permissions it fails looking for the wrong Subscription
I can't see which config file to change it to the Subscription when I installed the SaaS.Identity module (the config.json is correct for SaaS.Identity)
![image](https://github.com/Azure/azure-saas/assets/134180636/72553a63-69a7-4fb1-b716-3d4e81caec7d)

**Closed** 2023-06-07 09:17 UTC
Labels: bug

**Comment by 1iveowl** [comment] 2023-06-07 10:52
Awesome. Thanks for lette us know 👍
